# Spring application configuration
spring:

  application:
    name: SRW  # Name of the application

  server:
    port: 8080  # Server port
    session:
      timeout: 45m  # Set session timeout to 45 minutes

  jpa:
    hibernate:
      ddl-auto: update  # Auto-update schema
    show-sql: true  # Enables logging of SQL queries
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect  # MySQL dialect for Hibernate
    open-in-view: false  # Disable open-in-view to prevent lazy loading during view rendering

  cache:
    type: redis  # Redis as the cache provider

---
# Development profile configuration
spring:
  profiles:
    active: dev  # Set active profile to 'dev' for development environment

  datasource:
    url: ${DEV_DB_URL}  # Dynamic database URL for development
    username: ${DEV_DB_USERNAME}  # Dynamic database username for development
    password: ${DEV_DB_PASSWORD}  # Dynamic database password for development
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver

  redis:
    host: ${DEV_REDIS_HOST}  # Redis host for dev environment
    port: ${DEV_REDIS_PORT}  # Redis port for dev environment
    time-to-live: 180000  # TTL in milliseconds
    repositories:
      enabled: false  # Disable Redis repository scanning